#!/usr/bin/env bash
# This script prints  the content of the current directory in list format
# Thiw wil only  print the part of the name after the first dash

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
